name: Deploy site

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  deploy:
    runs-on: node:10
    steps:
      - run: npm install --quiet
      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}