name: Deploy site

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: node:10
    steps:
      - run: npm install --quiet
      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}