name: Deploy site

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update ubuntu
      - run: sudo apt update && sudo apt upgrade -y
      - run: sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
      - name: Install node
      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - run: sudo apt -y install nodejs
      - name: Install npm packages
      - run: npm install --quiet
      - name: Deploy site
      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}